### ISSUE TITLE
ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by codetaylor** [CoFH/NoNVFlash#1]
```
...
[12:54:21] [main/FATAL] [FML]: The following problems were captured during this phase
[12:54:21] [main/ERROR] [FML]: Caught exception from nonvflash (No Night Vision Flashing)
java.lang.ArrayIndexOutOfBoundsException: -1
	at java.util.ArrayList.elementData(ArrayList.java:418) ~[?:1.8.0_144]
	at java.util.ArrayList.remove(ArrayList.java:495) ~[?:1.8.0_144]
	at cofh.nonvflash.NoNVFlash.postInit(NoNVFlash.java:63) ~[NoNVFlash.class:?]
...
```

Full crash log: https://gist.github.com/codetaylor/b27a9719d550a46be6f1279f1fe0f4b1

**Comment by KingLemming** [comment]
This can literally only happen if you have another breaking the render pipeline.

Sorry, but you have something installed which is apparently a hard incompatibility.
